type PlatformKey = 'windows' | 'mac' | 'linux';
type Option = { label: string; value: PlatformKey };

export const PLATFORMS: Option[] = [
  { label: 'Windows', value: 'windows' },
  { label: 'Mac', value: 'mac' },
  { label: 'Linux', value: 'linux' },
];

export const PUBLISHER_CLASS = [
  { label: 'Hobbyist', value: 0 },
  { label: 'Indie', value: 1 },
  { label: 'AA', value: 2 },
  { label: 'AAA', value: 3 },
];

export const REQUIRED_AGE = [0, 3, 7, 12, 16, 18];

export const GENRES: { label: string; value: string }[] = [
  { label: 'Indie', value: 'Indie' },
  { label: 'Casual', value: 'Casual' },
  { label: 'Adventure', value: 'Adventure' },
  { label: 'Action', value: 'Action' },
  { label: 'Simulation', value: 'Simulation' },
  { label: 'Strategy', value: 'Strategy' },
  { label: 'RPG', value: 'RPG' },
  { label: 'Free To Play', value: 'Free_To_Play' },
  { label: 'Sports', value: 'Sports' },
  { label: 'Racing', value: 'Racing' },
] as const;

export const CATEGORIES: { label: string; value: string }[] = [
  { label: 'Single Player', value: 'Single_player' },
  { label: 'Family Sharing', value: 'Family_Sharing' },
  { label: 'Steam Achievements', value: 'Steam_Achievements' },
  { label: 'Steam Cloud', value: 'Steam_Cloud' },
  { label: 'Full Controller Support', value: 'Full_controller_support' },
  { label: 'Multi Player', value: 'Multi_player' },
  { label: 'Partial Controller Support', value: 'Partial_Controller_Support' },
  { label: 'Steam Trading Cards', value: 'Steam_Trading_Cards' },
  { label: 'PvP', value: 'PvP' },
  { label: 'Co-op', value: 'Co_op' },
  { label: 'Steam Leaderboards', value: 'Steam_Leaderboards' },
  { label: 'Remote Play Together', value: 'Remote_Play_Together' },
  { label: 'Online PvP', value: 'Online_PvP' },
  { label: 'Shared Split Screen', value: 'Shared_Split_Screen' },
  { label: 'Tracked Controller Support', value: 'Tracked_Controller_Support' },
  { label: 'VR Only', value: 'VR_Only' },
  { label: 'Shared Split Screen PvP', value: 'Shared_Split_Screen_PvP' },
  { label: 'Online Co-op', value: 'Online_Co_op' },
  { label: 'Stats', value: 'Stats' },
  { label: 'Shared Split Screen Co-op', value: 'Shared_Split_Screen_Co_op' },
] as const;

export const DEVELOPERS: { label: string; value: string }[] = [
  { label: 'AMAX Interactive', value: 'dev__AMAX_Interactive' },
  { label: 'Anamik Majumdar', value: 'dev__Anamik_Majumdar' },
  { label: 'Archor Wright', value: 'dev__Archor_Wright' },
  { label: 'Blender Games', value: 'dev__Blender_Games' },
  { label: "Cute Hannah's Games", value: 'dev__Cute_Hannah_s_Games' },
  { label: 'Cyber Keks', value: 'dev__Cyber_Keks' },
  { label: 'CyberStep Inc.', value: 'dev__CyberStep_Inc_' },
  { label: 'Dharker Studios', value: 'dev__Dharker_Studios' },
  { label: 'Dnovel', value: 'dev__Dnovel' },
  { label: 'Do Games Limited', value: 'dev__Do_Games_Limited' },
  { label: 'Eipix Entertainment', value: 'dev__Eipix_Entertainment' },
  { label: 'Elephant Games', value: 'dev__Elephant_Games' },
  { label: 'EpiXR Games UG', value: 'dev__EpiXR_Games_UG' },
  { label: 'Follow the fun', value: 'dev__Follow_the_fun' },
  { label: 'G MODE', value: 'dev__G_MODE' },
  { label: 'Gamesforgames', value: 'dev__Gamesforgames' },
  { label: 'GentleDriver', value: 'dev__GentleDriver' },
  { label: 'Hede', value: 'dev__Hede' },
  { label: 'Hosted Games', value: 'dev__Hosted_Games' },
  { label: 'IR Studio', value: 'dev__IR_Studio' },
  { label: 'KOEI TECMO GAMES CO LTD', value: 'dev__KOEI_TECMO_GAMES_CO_LTD_' },
  { label: 'Kairosoft Co Ltd', value: 'dev__Kairosoft_Co_Ltd' },
  { label: 'Kotovodk Studio', value: 'dev__Kotovodk_Studio' },
  { label: 'LTZinc', value: 'dev__LTZinc' },
  { label: 'Laush Dmitriy Sergeevich', value: 'dev__Laush_Dmitriy_Sergeevich' },
  { label: 'Miel', value: 'dev__Miel' },
  { label: 'Nikita Ghost RUS', value: 'dev__Nikita_Ghost_RUS_' },
  { label: 'Other', value: 'dev__Other' },
  { label: 'Piece Of Voxel', value: 'dev__Piece_Of_Voxel' },
  { label: 'RewindApp', value: 'dev__RewindApp' },
  { label: 'Rideon Works Co Ltd', value: 'dev__Rideon_Works_Co_Ltd_' },
  { label: 'Ripknot Systems', value: 'dev__Ripknot_Systems' },
  { label: 'SAT BOX', value: 'dev__SAT_BOX' },
  { label: 'Samet Acar', value: 'dev__Samet_Acar' },
  { label: 'Snkl Studio', value: 'dev__Snkl_Studio' },
  { label: 'Sokpop Collective', value: 'dev__Sokpop_Collective' },
  { label: 'Somer Games', value: 'dev__Somer_Games' },
  { label: 'Square Enix', value: 'dev__Square_Enix' },
  {
    label: 'Stegalosaurus Game Development',
    value: 'dev__Stegalosaurus_Game_Development',
  },
  { label: 'Tero Lunkka', value: 'dev__Tero_Lunkka' },
  { label: 'Valkeala Software', value: 'dev__Valkeala_Software' },
  { label: 'William at Oxford', value: 'dev__William_at_Oxford' },
  { label: 'Winged Cloud', value: 'dev__Winged_Cloud' },
  { label: 'magnussoft', value: 'dev__magnussoft' },
  { label: 'owlyboi', value: 'dev__owlyboi' },
  { label: 'dev__', value: 'dev___' },
] as const;

export const PUBLISHERS: { label: string; value: string }[] = [
  { label: '8floor', value: 'pub__8floor' },
  { label: 'Alawar Casual', value: 'pub__Alawar_Casual' },
  { label: 'Archor Games', value: 'pub__Archor_Games' },
  { label: 'Atari', value: 'pub__Atari' },
  { label: 'Big Fish Games', value: 'pub__Big_Fish_Games' },
  { label: 'Boogygames Studios', value: 'pub__Boogygames_Studios' },
  { label: 'Choice of Games', value: 'pub__Choice_of_Games' },
  { label: 'Conglomerate 5', value: 'pub__Conglomerate_5' },
  { label: 'Daedalic Entertainment', value: 'pub__Daedalic_Entertainment' },
  { label: 'Devolver Digital', value: 'pub__Devolver_Digital' },
  {
    label: 'DigiPen Institute of Technology',
    value: 'pub__DigiPen_Institute_of_Technology',
  },
  { label: 'Disney', value: 'pub__Disney' },
  { label: 'Electronic Arts', value: 'pub__Electronic_Arts' },
  { label: 'Fulqrum Publishing', value: 'pub__Fulqrum_Publishing' },
  { label: 'Gamera Games', value: 'pub__Gamera_Games' },
  { label: 'Gamesforgames', value: 'pub__Gamesforgames' },
  { label: 'GrabTheGames', value: 'pub__GrabTheGames' },
  { label: 'HH Games', value: 'pub__HH_Games' },
  { label: 'Hede', value: 'pub__Hede' },
  { label: 'Hosted Games', value: 'pub__Hosted_Games' },
  { label: 'KOEI TECMO GAMES CO LTD', value: 'pub__KOEI_TECMO_GAMES_CO_LTD_' },
  { label: 'KOMODO', value: 'pub__KOMODO' },
  { label: 'Kagura Games', value: 'pub__Kagura_Games' },
  { label: 'Laush Studio', value: 'pub__Laush_Studio' },
  { label: 'MangaGamer', value: 'pub__MangaGamer' },
  { label: 'Microids', value: 'pub__Microids' },
  { label: 'My Way Games', value: 'pub__My_Way_Games' },
  { label: 'Nacon', value: 'pub__Nacon' },
  { label: 'Nightdive Studios', value: 'pub__Nightdive_Studios' },
  { label: 'Other', value: 'pub__Other' },
  { label: 'PLAYISM', value: 'pub__PLAYISM' },
  { label: 'Piece Of Voxel', value: 'pub__Piece_Of_Voxel' },
  { label: 'Pixel Games UK', value: 'pub__Pixel_Games_UK' },
  { label: 'PlayWay S.A.', value: 'pub__PlayWay_S_A_' },
  { label: 'Plug In Digital', value: 'pub__Plug_In_Digital' },
  { label: 'SA Industry', value: 'pub__SA_Industry' },
  { label: 'SEGA', value: 'pub__SEGA' },
  { label: 'Sekai Project', value: 'pub__Sekai_Project' },
  { label: 'Shiravune', value: 'pub__Shiravune' },
  { label: 'Slitherine Ltd.', value: 'pub__Slitherine_Ltd_' },
  { label: 'Sokpop Collective', value: 'pub__Sokpop_Collective' },
  { label: 'Square Enix', value: 'pub__Square_Enix' },
  { label: 'Strategy First', value: 'pub__Strategy_First' },
  { label: 'THQ Nordic', value: 'pub__THQ_Nordic' },
  { label: 'Tero Lunkka', value: 'pub__Tero_Lunkka' },
  { label: 'Ubisoft', value: 'pub__Ubisoft' },
  { label: 'Ziggurat', value: 'pub__Ziggurat' },
  { label: 'indie.io', value: 'pub__indie_io' },
  { label: 'tinyBuild', value: 'pub__tinyBuild' },
] as const;
